package biali.fitmanager.backend.service;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.util.List;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Map;
import java.util.stream.Collectors;

import org.springframework.stereotype.Service;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

import biali.fitmanager.backend.model.AppUser;
import biali.fitmanager.backend.repository.AppUserRepository;

@Service
public class PdfReportService {

    private final AppUserRepository appUserRepository;
    private final biali.fitmanager.backend.repository.TrainerClientRepository trainerClientRepository;

    public PdfReportService(AppUserRepository appUserRepository,
                            biali.fitmanager.backend.repository.TrainerClientRepository trainerClientRepository) {
        this.appUserRepository = appUserRepository;
        this.trainerClientRepository = trainerClientRepository;
    }

    public byte[] generateUsersReport(String generatedBy) {
        List<AppUser> users = appUserRepository.findAll();
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4.rotate(), 36, 36, 36, 36);
            PdfWriter.getInstance(doc, baos);
            doc.open();

            Font titleFont = new Font(Font.HELVETICA, 16, Font.BOLD);
            Font normal = new Font(Font.HELVETICA, 10);
            Font small = new Font(Font.HELVETICA, 9);

                Paragraph title = new Paragraph("Users report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            doc.add(title);

                Paragraph meta = new Paragraph("Generated by: " + (generatedBy == null ? "unknown" : generatedBy) + " - " + java.time.ZonedDateTime.now().format(DateTimeFormatter.ISO_OFFSET_DATE_TIME), normal);
                meta.setSpacingAfter(8f);
                doc.add(meta);

                // Statystyki dla administratora
                int totalUsers = users.size();
                long trainers = users.stream().filter(u -> u.getRole() != null && u.getRole().equalsIgnoreCase("TRAINER")).count();
                long clients = users.stream().filter(u -> u.getRole() != null && u.getRole().equalsIgnoreCase("CLIENT")).count();
                BigDecimal totalBalance = users.stream()
                    .map(u -> u.getAccountBalance() == null ? BigDecimal.ZERO : u.getAccountBalance())
                    .reduce(BigDecimal.ZERO, BigDecimal::add);

                Paragraph stats = new Paragraph(String.format("Total users: %d    Trainers: %d    Clients: %d    Total balance: %s",
                    totalUsers, trainers, clients, formatBalance(totalBalance)), normal);
                stats.setSpacingAfter(12f);
                doc.add(stats);

            PdfPTable table = new PdfPTable(new float[]{1f, 3f, 2.5f, 2.5f, 2f, 2.5f, 3f, 2f});
            table.setWidthPercentage(100);

            addHeaderCell(table, "ID");
            addHeaderCell(table, "Email");
            addHeaderCell(table, "First Name");
            addHeaderCell(table, "Last Name");
            addHeaderCell(table, "Role");
            addHeaderCell(table, "Phone");
            addHeaderCell(table, "Created At");
            addHeaderCell(table, "Balance");

            for (AppUser u : users) {
                table.addCell(new PdfPCell(new Phrase(u.getId() == null ? "" : u.getId().toString(), small)));
                table.addCell(new PdfPCell(new Phrase(u.getEmail() == null ? "" : u.getEmail(), small)));
                table.addCell(new PdfPCell(new Phrase(u.getFirstName() == null ? "" : u.getFirstName(), small)));
                table.addCell(new PdfPCell(new Phrase(u.getLastName() == null ? "" : u.getLastName(), small)));
                table.addCell(new PdfPCell(new Phrase(u.getRole() == null ? "" : u.getRole(), small)));
                table.addCell(new PdfPCell(new Phrase(u.getPhoneNumber() == null ? "" : u.getPhoneNumber(), small)));
                table.addCell(new PdfPCell(new Phrase(formatCreatedAt(u.getCreatedAt()), small)));
                PdfPCell balCell = new PdfPCell(new Phrase(formatBalance(u.getAccountBalance()), small));
                balCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                table.addCell(balCell);
            }

            doc.add(table);

                // Prosty wykres słupkowy: trenerzy vs klienci
                Paragraph chartTitle = new Paragraph("Users by role (visual):", normal);
                chartTitle.setSpacingBefore(12f);
                chartTitle.setSpacingAfter(6f);
                doc.add(chartTitle);

                int maxVal = Math.max((int) trainers, (int) clients);
                if (maxVal == 0) maxVal = 1;

                PdfPTable chartTable = new PdfPTable(new float[]{2f, 8f, 2f});
                chartTable.setWidthPercentage(60);
                chartTable.getDefaultCell().setBorder(PdfPCell.NO_BORDER);

                // Wiersz trenerów
                chartTable.addCell(new Phrase("Trainers", small));
                int maxBlocks = 30;
                int trainersBlocks = Math.round((float) trainers / maxVal * maxBlocks);
                String trainersBar = trainersBlocks > 0 ? "▇".repeat(trainersBlocks) : "";
                chartTable.addCell(new Phrase(trainersBar, small));
                chartTable.addCell(new Phrase(String.valueOf(trainers), small));

                // Wiersz klientów
                chartTable.addCell(new Phrase("Clients", small));
                int clientsBlocks = Math.round((float) clients / maxVal * maxBlocks);
                String clientsBar = clientsBlocks > 0 ? "▇".repeat(clientsBlocks) : "";
                chartTable.addCell(new Phrase(clientsBar, small));
                chartTable.addCell(new Phrase(String.valueOf(clients), small));

                doc.add(chartTable);

                // Przypisania trener -> klienci
                Paragraph assignTitle = new Paragraph("Trainer assignments:", normal);
                assignTitle.setSpacingBefore(12f);
                assignTitle.setSpacingAfter(6f);
                doc.add(assignTitle);

                PdfPTable assignTable = new PdfPTable(new float[]{3f, 7f});
                assignTable.setWidthPercentage(100);
                addHeaderCell(assignTable, "Trainer");
                addHeaderCell(assignTable, "Clients");

                // Mapa trainerId -> lista clientId
                Map<Integer, List<Integer>> mapping = trainerClientRepository.findAll().stream()
                    .collect(Collectors.groupingBy(TrainerClient -> TrainerClient.getTrainerId(),
                        Collectors.mapping(tc -> tc.getClientId(), Collectors.toList())));

                // Lista trenerów
                List<AppUser> trainersList = users.stream()
                    .filter(u -> u.getRole() != null && u.getRole().equalsIgnoreCase("TRAINER"))
                    .toList();

                for (AppUser t : trainersList) {
                assignTable.addCell(new PdfPCell(new Phrase((t.getFirstName() == null ? "" : t.getFirstName()) + " " + (t.getLastName() == null ? "" : t.getLastName()) + " <" + (t.getEmail()==null?"":t.getEmail()) + ">", small)));
                List<Integer> cids = mapping.getOrDefault(t.getId(), List.of());
                String clientsStr = cids.stream()
                    .map(id -> users.stream().filter(u -> id.equals(u.getId())).findFirst().map(u -> u.getFirstName() + " " + u.getLastName() + " (" + u.getEmail() + ")").orElse("<unknown>"))
                    .collect(Collectors.joining(", "));
                assignTable.addCell(new PdfPCell(new Phrase(clientsStr.isBlank() ? "-" : clientsStr, small)));
                }

                doc.add(assignTable);
            doc.close();
            return baos.toByteArray();
        } catch (Exception ex) {
            throw new RuntimeException("Failed to generate PDF", ex);
        }
    }

    private void addHeaderCell(PdfPTable table, String text) {
        Font head = new Font(Font.HELVETICA, 11, Font.BOLD);
        PdfPCell cell = new PdfPCell(new Phrase(text, head));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        // zostaw tło bez kolorowania, aby uniknąć zależności od klasy Color
        table.addCell(cell);
    }

    private String formatCreatedAt(LocalDateTime dt) {
        if (dt == null) return "";
        return dt.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
    }

    private String formatBalance(BigDecimal b) {
        if (b == null) return "0.00";
        return b.setScale(2, RoundingMode.HALF_UP).toString() + " PLN";
    }
}
