package biali.fitmanager.backend.service;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;

import org.springframework.stereotype.Service;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

import biali.fitmanager.backend.model.AppUser;
import biali.fitmanager.backend.repository.AppUserRepository;

@Service
public class PdfReportService {

    private final AppUserRepository appUserRepository;

    public PdfReportService(AppUserRepository appUserRepository) {
        this.appUserRepository = appUserRepository;
    }

    public byte[] generateUsersReport(String generatedBy) {
        List<AppUser> users = appUserRepository.findAll();
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4.rotate(), 36, 36, 36, 36);
            PdfWriter.getInstance(doc, baos);
            doc.open();

            Font titleFont = new Font(Font.HELVETICA, 16, Font.BOLD);
            Font normal = new Font(Font.HELVETICA, 10);

            Paragraph title = new Paragraph("Users report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            doc.add(title);

            Paragraph meta = new Paragraph("Generated by: " + (generatedBy == null ? "unknown" : generatedBy) + " - " + java.time.ZonedDateTime.now().format(DateTimeFormatter.ISO_OFFSET_DATE_TIME), normal);
            meta.setSpacingAfter(12f);
            doc.add(meta);

            PdfPTable table = new PdfPTable(new float[]{1f, 3f, 3f, 3f, 2f, 3f});
            table.setWidthPercentage(100);

            addHeaderCell(table, "ID");
            addHeaderCell(table, "Email");
            addHeaderCell(table, "First Name");
            addHeaderCell(table, "Last Name");
            addHeaderCell(table, "Role");
            addHeaderCell(table, "Phone");

            for (AppUser u : users) {
                table.addCell(new PdfPCell(new Phrase(u.getId() == null ? "" : u.getId().toString(), normal)));
                table.addCell(new PdfPCell(new Phrase(u.getEmail() == null ? "" : u.getEmail(), normal)));
                table.addCell(new PdfPCell(new Phrase(u.getFirstName() == null ? "" : u.getFirstName(), normal)));
                table.addCell(new PdfPCell(new Phrase(u.getLastName() == null ? "" : u.getLastName(), normal)));
                table.addCell(new PdfPCell(new Phrase(u.getRole() == null ? "" : u.getRole(), normal)));
                table.addCell(new PdfPCell(new Phrase(u.getPhoneNumber() == null ? "" : u.getPhoneNumber(), normal)));
            }

            doc.add(table);
            doc.close();
            return baos.toByteArray();
        } catch (Exception ex) {
            throw new RuntimeException("Failed to generate PDF", ex);
        }
    }

    private void addHeaderCell(PdfPTable table, String text) {
        Font head = new Font(Font.HELVETICA, 11, Font.BOLD);
        PdfPCell cell = new PdfPCell(new Phrase(text, head));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);
    }
}
